app/Console/Commands/RegisterAdmin.php
app/Http/Controllers/Admin/Auth/LoginController.php
app/Http/Requests/Auth/AdminLoginRequest.php
app/Models/Admin.php
app/Models/User.php
resources/views/admin/auth/login.blade.php
resources/views/admin/dashboard.blade.php
routes/admin-auth.php
routes/web.php

feat(Auth): add breeze admin auth

---

app/Http/Controllers/Admin/Auth/LoginController.php
app/Http/Controllers/Admin/DashboardController.php
bootstrap/app.php
resources/views/admin/app.blade.php
resources/views/admin/dashboard.blade.php
resources/views/admin/layouts/header.blade.php
resources/views/admin/layouts/sidebar.blade.php
resources/views/layouts/navigation.blade.php
routes/admin.php
routes/auth.php
routes/web.php
tailwind.config.js

Closes: create_admin_dashboard

feat(admin): add admin dashboard design

---

app/Contracts/Admin/CategoryShowServiceContract.php
app/Http/Controllers/Admin/CategoryController.php
app/Models/Category.php
app/Providers/AppServiceProvider.php
app/Repository/Admin/CategoryRepository.php
app/Service/Admin/Category/ShowAll/ShowAllService.php
app/Service/Admin/Category/ShowForSelect/Dto/CollectionDto.php
app/Service/Admin/Category/ShowForSelect/Dto/Dto.php
app/Service/Admin/Category/ShowForSelect/ShowService.php
resources/views/admin/category/create.blade.php
resources/views/admin/category/index.blade.php
resources/views/admin/layouts/sidebar.blade.php
resources/views/vendor/pagination/tailwind.blade.php
routes/admin.php

feat(admin): add category list

---

app/Console/Commands/RegisterAdmin.php
app/Repository/Article/ShowMainArticle/Dto.php
resources/views/index.blade.php

refactor: add output article on main page

---

.github/workflows/deploy.yml

feat: add ci cd github

---

resources/views/admin/dashboard.blade.php

feat: test ci cd github

---

resources/views/layouts/app.blade.php

feat: add meta tag

---

resources/views/layouts/nav.blade.php

refactor: change nav

---

app/Http/Controllers/ArticleController.php
resources/css/app.css
resources/js/app.js
resources/views/article/show.blade.php
resources/views/layouts/app.blade.php
routes/web.php

feat: add view article functional

---

.github/workflows/deploy.yml

feat: add backup before pull

---

resources/views/layouts/nav.blade.php

refactor: test ci cd github

---

app/Contracts/Index/ShowContract.php
app/Repository/Article/ShowMainArticle/Query.php
app/Service/Article/MainNews/Handler.php
resources/views/index.blade.php

refactor: add stub if articles table empty

---

docker-compose.yml

refactor: change docker compose

---

resources/js/admin/shortDescription-length.js
resources/js/admin/slug-transform.js
resources/js/admin/title-length.js
resources/views/admin/article/create.blade.php
resources/views/admin/layouts/app.blade.php

and automatically slug formater
Closes: #40

feat: add count length title, shortDescription

---

resources/views/article/show.blade.php
resources/views/index.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/header.blade.php
resources/views/layouts/nav.blade.php
resources/views/layouts/newsletter.blade.php
routes/admin.php
tailwind.config.js

feat: change html

---

.env.example
docker-compose.yml

fix(config): change docker-compose.yml

---

README.md

v1 - документация "как развернуть проект для разработки"

project manual

---

README.md
app/Http/Controllers/Admin/ArticleController.php
app/Http/Controllers/ArticleController.php
app/Http/Requests/Admin/Article/StoreRequest.php
app/Http/Requests/Admin/Article/UpdateRequest.php
app/Http/Requests/Auth/AdminLoginRequest.php
app/Models/Article.php
app/Service/Admin/Article/Show/Dto.php
app/Service/Admin/Article/Store/StoreDto.php
app/Service/Admin/Article/Store/StoreService.php
app/Service/Admin/Article/Update/UpdateService.php
database/migrations/2024_08_28_205956_add_user_to_articles_table.php
resources/views/article/show.blade.php
resources/views/index.blade.php

add admin_id to article,
article show fix
article request status fix

fix(article): article admin_id

---

app/Repository/Article/GetSimilar/GetSimilarDto.php
app/Repository/Article/GetSimilar/Query.php
app/Repository/Article/GetSimilar/ViewCollection.php
resources/views/article/show.blade.php

feat: change link for similar articles

---

resources/views/index.blade.php
resources/views/layouts/breadcrumbs.blade.php
resources/views/layouts/header.blade.php

style: change index page mobile style
